### ISSUE TITLE
Create MapD documentWidgetFactoryOptions and fileTypes

### ISSUE THREAD

**Issue by tonyfast** [Quansight/jupyterlab-omnisci#1]
In `index.ts`, supply a MapD specific file type that includes the mapd icon.  When a user right clicks a new panel will open with the output.

The code below not correct, but I was able to experiment with some of the user behaviors with 

	const extensions: IRenderMime.IExtension | IRenderMime.IExtension[] = [
	  {
	    id: 'jupyterlab-mapd:factory',
	    rendererFactory,
	    dataType: 'json',
	    documentWidgetFactoryOptions: [{
	        name: 'Mapd',
	        primaryFileType: 'mapd',
	        fileTypes: ['mapd', 'json'],
	        defaultFor: ['mapd'],
	      },],
	      fileTypes: [{
	        mimeTypes: ['application/vdom.v1+json'],
	        name: 'mapd',
	        extensions: ['.mapd', '.mapd.json', '.json'],
	        iconClass: 'jp-MaterialIcon jp-VegaIcon',
	      }]
	  }
	];

This will elevate the mapd branding in Jupyterlab and provide a specific behavior for a vega file containing a query.

**Comment by gnestor** [comment]
@tonyfast I'm happy to work on this. What would the contents of a mapd document look like?
