### ISSUE TITLE
Password shown in plain text

### ISSUE THREAD

**Issue by randyzwitch** [Quansight/jupyterlab-omnisci#18]
When clicking on the MapD button, the password is shown in plain text. Replace with ********* to minimize over-the-shoulder password stealing

<img width="1005" alt="screen shot 2018-08-14 at 8 33 42 am" src="https://user-images.githubusercontent.com/2762787/44091960-187af528-9f9d-11e8-9ed8-3e887a31846e.png">

**Comment by ian-r-rose** [comment]
This has been fixed, thanks @randyzwitch.

**Comment by randyzwitch** [comment]
Awesome!
