### ISSUE TITLE
Integration with vega lite aggregates 

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight/jupyterlab-omnisci#24]
We want to be able to take a Vega Lite spec that depends on data from a MapD SQL query and pre-compute the aggregates so that only those have to be sent to the client, instead of doing the aggregates on the client. 

One way to do this is to output a Vega Lite spec that has a mapd query string as the data, from the frontend, then use javascript to extract out the aggregates from this spec and call the mapd backend from the frontend.

- [ ] Create Altair transformer so that when you call Altair with ibis mapd query it will output new MimeType for Vega Lite with mapd SQL and connection info (this is like the MapD Vega Lite spec, but it  conforms to the actual Vega Lite spec except for having SQL/conn info as the data)
- [ ] We create a JupyterLab renderer for this mimetype that uses https://github.com/vega/vega-lite/pull/3945 (once it is merged in) to extract out the aggregates from the vega lite spec and define transformations of them into SQL.
- [ ] Use the [mapd javascript API](https://omnisci.github.io/mapd-connector/docs/) to query the database with the updated query, feed into Vega Lite

**Comment by niviksha** [comment]
@saulshanabrook probably implied here, but we'd want the SQL generator to be usable in both python and javascript contexts.

**Comment by saulshanabrook** [comment]
@niviksha  do you mean so that it uses the Python mapd API instead of the JavaScript one or so you mean someone in a Python notebook should be able to use this functionality? 

If the first is required, then we need to go from python -> JavaScript (to use the Vega lite aggregate transforms that are being implemented) -> python again. 

If just the second is required we can just go from python -> JavaScript.

**Comment by saulshanabrook** [comment]
Notes:

https://github.com/vega/vega-lite/blob/34ee3f719e8327b3697554493c5c1f52e7269605/test/transformextract.test.ts

https://github.com/vega/vega-lite-transforms2sql/blob/3b360144305a6cec79792036049e8a920e4d2c9e/index.ts#L80-L82

**Comment by saulshanabrook** [comment]
extract transform VL code https://github.com/vega/vega-lite/blob/c8001067cfd273973659edf089a4916918184ec9/src/transformextract.ts

**Comment by saulshanabrook** [comment]
Also this https://github.com/vega/vega-lite/pull/3945/files#diff-f4dfe4675db9dc9fb172b7ca28480eda

**Comment by saulshanabrook** [comment]
Closing this since we have an implementation working now, but not through this pipeline.
