### ISSUE TITLE
Avoid using global variables to async render to display handle or widget

### ISSUE THREAD

**Issue by gnestor** [Quansight/jupyterlab-omnisci#50]
When the [`extract` argument is set to `True`](https://github.com/Quansight/jupyterlab-omnisci/blob/master/jupyterlab_omnisci/altair.py#L110) in our ibis renderer for altair, we have to [send the vega-lite spec to the front-end (via comms)](https://github.com/Quansight/jupyterlab-omnisci/blob/master/jupyterlab_omnisci/altair.py#L202) so that the [vega-lite JS library can transform it using extractTransforms](https://github.com/Quansight/jupyterlab-omnisci/blob/master/src/extract-vega-lite.ts#L28) and send it back to the kernel. In order to update the output with the extracted spec, we have to pass a callback from the `ibis_renderer`to `extract_data`. The default callback behavior is to [update a display that was created in the first pass of `ibis_renderer`](https://github.com/Quansight/jupyterlab-omnisci/blob/master/jupyterlab_omnisci/altair.py#L120-L121). If we're trying to use ipywidgets or interactive vdom, then we need to [update a **specific** widget instance](https://github.com/Quansight/jupyterlab-omnisci/blob/master/jupyterlab_omnisci/altair.py#L114-L118) or [display handle (containing the vdom)](https://github.com/Quansight/jupyterlab-omnisci/pull/49/files#diff-6b1f5479dd8a5c53c2dd6b9df47c77b1R127).

Given that context, the issue is that the altair renderer API accept a pure function, so it doesn't pass a `self` argument. Therefore, we are unable to associate a display handle, display ID, or widget instance with a chart, so we are currently forced to [set a global in altair.py](https://github.com/Quansight/jupyterlab-omnisci/blob/master/jupyterlab_omnisci/altair.py#L141) and and [unset it](https://github.com/Quansight/jupyterlab-omnisci/blob/master/jupyterlab_omnisci/altair.py#L143) so it doesn't creep into other chart instances.

Potential solutions:

* Use asyncio to make the comm roundtrip synchronous vs. asynchronous. This would allow us to keep a reference to the widget instance or display handle and not depend on a global variable. 
  * We spoke with @Carreau this week who is very familiar with asyncio and he doesn't think it's possible
* Change the altair renderer API to include a `self` argument 
* Reimplement the `extractTransforms` in Python
* Create a custom altair widget (ipywidget or vdom) and instruct users to use that vs altair directly

@tonyfast suggested that we send the `display_id` along in the comm message from Python to JS but the issue is that the `display_id` is set in `get_display` or `interactive_chart`, both of which are top-level functions along with `ibis_renderer`, and since `ibis_renderer` is only passed `spec` as argument, we don't have any way to pass a display handle or widget to it other than setting a global. 

cc @saulshanabrook

**Comment by saulshanabrook** [comment]
Since we moved to using Vega transforms, this issue is less relevant. We still are using globals, but they seem even harder to remove now. Closing for now, we can reopen if we want to come back to this.
