### ISSUE TITLE
Interactive Visualizations

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight/jupyterlab-omnisci#54]
We want to support interactive Altair visualizations recomputing omnisci data. 

Game plan:

1. Create global mapping of hash -> ibis expression called `HASH_TO_IBIS`
2. Create new Altair transformer (`vega-ibis`) which:
   1. sets "name" of dataset in vega lite to be `ibis+{hash(expr)}`
   2. saves expression in global lookup table
3. Create a new Altair renderer called `vega-ibis` which:
   3. exports vega lite with new vega lite mimetype
3. Create new vega lite renderer for mimetype (`application/vnd.vegalite.v3+json; ibis=true`) which:
   1. Transforms vega lite to vega
   2. Extracts out data and transforms of vega and moves it to new transform, see example below.
   3. Renders Vega with vega embed
4. Create and register new vega transform (`ibis`) which:
   1. Registers itself as dependency of the dependencies of all it's transforms
   2. On updated data, opens a `vega-ibis` comm to the kernel and sends over itself and the data
   3. on a response, resolves itself and returns 
5. Setup a comm handler on the (`vega-ibis`) on kernel side. On each new comm it receives it should:
    1. Takes in initial query hash and transforms and signal values
    2. Looks up initial ibis query
    3. iterates through existing transform and values and creates updated ibis query
    4. query database
    5. Send result back on comm directly or save to file and send filename

Example of initial Vega data:

```json
{
  "name":"ibis_13234324523455",
  "transform":[
    {
      "type":"filter",
      "expr":"!(length(data(\"month_store\"))) || (vlSelectionTest(\"month_store\", datum))"
    },
    {
      "type":"aggregate",
      "groupby":[
        "flight_dayofmonth"
      ],
      "ops":[
        "average"
      ],
      "fields":[
        "depdelay"
      ],
      "as":[
        "average_depdelay"
      ]
    }
  ]
}
```

Transformed query:

```json
{
  "name":"ibis_13234324523455",
  "transform":[
    {
      "type":"ibis",
      "hash":"13234324523455",
      "transform":[
        {
          "type":"filter",
          "expr":"!(length(data(\"month_store\"))) || (vlSelectionTest(\"month_store\", datum))"
        },
        {
          "type":"aggregate",
          "groupby":[
            "flight_dayofmonth"
          ],
          "ops":[
            "average"
          ],
          "fields":[
            "depdelay"
          ],
          "as":[
            "average_depdelay"
          ]
        }
      ]
    }
  ]
}
```

**Comment by saulshanabrook** [comment]
@domoritz and I just had a little chat about this issue. 

The high level goal is to take a Vega spec with several transforms and fuse them into one that will have the same semantics but execute on a database far away.


Dominik pointed out there are potentially two ways of doing this:

1. We could replace the existing transforms with a new one, like I sketched out above. That new transform would have to depend on the signals that all the existing transforms depended on.
2. We could first turn the Vega spec into the dataflow graph. Then when we have the graph, replace some of the nodes.

Option 2 is appealing because then the dependencies are already computed, so it seems like it would be easier to take their union. But we were not sure if it is possible to mutate the graph like that.

Option 1 would be nice, because then we can see the result before executing and we know we can add custom transforms.

**Comment by domoritz** [comment]
Here is what I took away from our meeting.

You would like to take an existing Vega specification and fuse transforms into a single ibis transform. The ibis transform will work similar to the [omnisci transform](https://github.com/vega/vega-transform-omnisci-core) in that every time the transform gets called, it makes an async request to the backend and then continues the execution when the request returns. What's tricky is that the transforms you want to fuse may be using signals and so you have to make sure that your ibis transform uses all the signals that are in the original transforms. There are two ways to do this. First, you could analyze the Vega spec and create a signal that constructs the `transform` property above. Second, you could parse the spec with Vega and do all your transformations in the Vega dataflow. What's good about the second approach is that the signals are already all wired up. However, I don't know enough about the internals to see whether it makes sense (@jheer will know).

**Comment by saulshanabrook** [comment]
```
{
  "name":"ibis_13234324523455",
  "transform":[
{
"type": "ibis",
"hash": 13234324523455
},
    {
      "type":"filter",
      "expr":"!(length(data(\"month_store\"))) || (vlSelectionTest(\"month_store\", datum))"
    },
    {
      "type":"aggregate",
      "groupby":[
        "flight_dayofmonth"
      ],
      "ops":[
        "average"
      ],
      "fields":[
        "depdelay"
      ],
      "as":[
        "average_depdelay"
      ]
    }
  ]
}
``

**Comment by domoritz** [comment]
From @jheer:

Yes, `vega.parse` gives you the dataflow graph description _prior_ to instantiation by a Vega `View` (using the methods of the `vega-runtime` package). That would be a natural place to make edits. All transforms are included, and all expressions have at that point been parsed and converted to code-generated JavaScript.

If you look at https://observablehq.com/@vega/how-vega-works, go to the section “Parsing a Vega Specification” and expand the `parsedSpec` variable. There are a list of dataflow operator descriptions (“entries”) in the `operators` array, including `aggregate`. All transforms (filter, aggregate, window, formula, etc) defined in the top-level scope will show up in this list. However, also note that if the spec involves nested groups, you’ll need to look deeper into subcontexts for any transforms defined within nested scopes.

**Comment by saulshanabrook** [comment]
>  All transforms are included, and all expressions have at that point been parsed and converted to code-generated JavaScript.


OK I must be missing something then, because in this example ([VegaLite spec](https://github.com/Quansight/explore-vega/blob/9204ce21c5948db9b205a9bd33e1c77b6c7767da/index.js#L4-L23), [Vega spec](https://github.com/Quansight/explore-vega/blob/6964c18e4d4bd08100c43a1967bfdf393148662e/vega.json), [Vega graph](https://github.com/Quansight/explore-vega/blob/9204ce21c5948db9b205a9bd33e1c77b6c7767da/graph.json)), I cannot find where the transforms from the Vega spec end up in the graph.

**Comment by saulshanabrook** [comment]
@ian-r-rose and I had a productive call today about this and created [a flow chart with some background notes](https://docs.google.com/drawings/d/1m3LC4nRw_Q7GGNHi-wEaQiixKys6vXE55rlIbC1ez_A/edit?usp=sharing)
![Mapd Vega](https://user-images.githubusercontent.com/1186124/56527439-ac416500-651b-11e9-81e6-adf6422afef4.png)

One interesting conclusion is that we are going to try to compile/transform the Vega lite spec in Python land, instead of in JS land. This is nice, because then we can do all of the compilation logic in Python.

**Comment by jheer** [comment]
@saulshanabrook I don't think I totally follow the idea to compile/transform VL within Python. Are you proposing to bypass the Vega-Lite JavaScript library entirely and write your own VL->Vega compiler? Or did I completely miss something here? (I'm assuming the transform extraction and re-writing is happening at the Vega, not Vega-Lite level, though either is possible in theory, given appropriate support from an underlying layer.)

Regarding your earlier post about where the transforms reside: Consider this basic [Vega-Lite historgram example](https://vega.github.io/editor/#/examples/vega-lite/histogram). If you take the resulting Vega output, remove the axis definitions for convenience sake here, and call `vega.parse` on it, you get the following dataflow graph description:

<details>
<summary>Vega Dataflow Graph Description</summary>

```json
{
  "background": null,
  "operators": [
    {
      "id": 0,
      "type": "operator",
      "root": true
    },
    {
      "id": 1,
      "type": "operator",
      "value": 200,
      "signal": "width"
    },
    {
      "id": 2,
      "type": "operator",
      "value": 200,
      "signal": "height"
    },
    {
      "id": 3,
      "type": "operator",
      "value": {
        "top": 5,
        "bottom": 5,
        "left": 5,
        "right": 5
      },
      "signal": "padding"
    },
    {
      "id": 4,
      "type": "operator",
      "value": {
        "type": "pad"
      },
      "signal": "autosize"
    },
    {
      "id": 5,
      "type": "operator",
      "value": null,
      "params": {},
      "update": "{\"offset\":18,\"direction\":\"horizontal\",\"left\":{\"direction\":\"vertical\"},\"right\":{\"direction\":\"vertical\"}}"
    },
    {
      "id": 6,
      "type": "collect",
      "data": {
        "root": [
          "input",
          "output"
        ]
      }
    },
    {
      "id": 7,
      "type": "encode",
      "params": {
        "pulse": {
          "$ref": 6
        },
        "encoders": {
          "$encode": {
            "enter": {
              "$expr": "var o=item,datum=o.datum,$;o[\"fill\"]=\"transparent\";o[\"stroke\"]=\"#ddd\";o[\"x\"]=0;o[\"y\"]=0;return 1;",
              "$fields": [],
              "$output": [
                "fill",
                "stroke",
                "x",
                "y"
              ]
            },
            "update": {
              "$expr": "var o=item,datum=o.datum,$;o[\"width\"]=_[\"$width\"];o[\"height\"]=_[\"$height\"];return 1;",
              "$fields": [],
              "$output": [
                "width",
                "height"
              ]
            }
          }
        },
        "$width": {
          "$ref": 1
        },
        "$height": {
          "$ref": 2
        }
      }
    },
    {
      "id": 9,
      "type": "sieve",
      "params": {
        "pulse": {
          "$ref": 7
        }
      }
    },
    {
      "id": 10,
      "type": "scale",
      "params": {
        "type": "linear",
        "domain": {
          "$ref": 22
        },
        "range": [
          0,
          {
            "$ref": 1
          }
        ],
        "bins": {
          "$ref": 13
        },
        "zero": false
      },
      "scale": "x"
    },
    {
      "id": 11,
      "type": "scale",
      "params": {
        "type": "linear",
        "domain": {
          "$ref": 23
        },
        "range": [
          {
            "$ref": 2
          },
          0
        ],
        "nice": true,
        "zero": true
      },
      "scale": "y"
    },
    {
      "id": 12,
      "type": "proxy",
      "params": {
        "value": {
          "$ref": 15
        }
      },
      "signal": "bin_maxbins_10_IMDB_Rating_extent"
    },
    {
      "id": 13,
      "type": "proxy",
      "params": {
        "value": {
          "$ref": 16
        }
      },
      "signal": "bin_maxbins_10_IMDB_Rating_bins"
    },
    {
      "id": 14,
      "type": "collect",
      "value": {
        "$request": "data/movies.json",
        "$format": {
          "type": "json"
        }
      },
      "params": {},
      "metadata": {
        "source": true
      },
      "data": {
        "source_0": [
          "input"
        ]
      }
    },
    {
      "id": 15,
      "type": "extent",
      "value": null,
      "params": {
        "field": {
          "$field": "IMDB_Rating"
        },
        "pulse": {
          "$ref": 14
        }
      },
      "refs": null,
      "metadata": {}
    },
    {
      "id": 16,
      "type": "bin",
      "value": null,
      "params": {
        "field": {
          "$field": "IMDB_Rating"
        },
        "maxbins": 10,
        "extent": {
          "$ref": 12
        },
        "as": [
          "bin_maxbins_10_IMDB_Rating",
          "bin_maxbins_10_IMDB_Rating_end"
        ],
        "pulse": {
          "$ref": 15
        }
      },
      "refs": null,
      "metadata": {
        "modifies": true
      }
    },
    {
      "id": 17,
      "type": "aggregate",
      "value": null,
      "params": {
        "groupby": [
          {
            "$field": "bin_maxbins_10_IMDB_Rating"
          },
          {
            "$field": "bin_maxbins_10_IMDB_Rating_end"
          }
        ],
        "ops": [
          "count"
        ],
        "fields": [
          {
            "$field": null
          }
        ],
        "as": [
          "__count"
        ],
        "pulse": {
          "$ref": 16
        }
      },
      "metadata": {
        "generates": true,
        "changes": true
      }
    },
    {
      "id": 18,
      "type": "collect",
      "params": {
        "pulse": {
          "$ref": 17
        }
      },
      "metadata": {
        "source": true
      }
    },
    {
      "id": 19,
      "type": "filter",
      "value": null,
      "params": {
        "expr": {
          "$expr": "((datum[\"bin_maxbins_10_IMDB_Rating\"]!==null)&&(!isNaN(datum[\"bin_maxbins_10_IMDB_Rating\"])))",
          "$fields": [
            "bin_maxbins_10_IMDB_Rating"
          ],
          "$params": {}
        },
        "pulse": {
          "$ref": 18
        }
      },
      "metadata": {
        "changes": true
      }
    },
    {
      "id": 20,
      "type": "collect",
      "params": {
        "pulse": {
          "$ref": 19
        }
      },
      "metadata": {
        "source": true
      },
      "data": {
        "source_0": [
          "output"
        ]
      }
    },
    {
      "id": 21,
      "type": "sieve",
      "params": {
        "pulse": {
          "$ref": 20
        }
      },
      "data": {
        "source_0": [
          "values"
        ]
      }
    },
    {
      "id": 22,
      "type": "operator",
      "value": null,
      "params": {
        "$bin_maxbins_10_IMDB_Rating_bins": {
          "$ref": 13
        }
      },
      "update": "[_[\"$bin_maxbins_10_IMDB_Rating_bins\"].start,_[\"$bin_maxbins_10_IMDB_Rating_bins\"].stop]"
    },
    {
      "id": 23,
      "type": "extent",
      "params": {
        "field": {
          "$field": "__count"
        },
        "pulse": {
          "$ref": 20
        }
      }
    },
    {
      "id": 24,
      "type": "datajoin",
      "params": {
        "pulse": {
          "$ref": 20
        },
        "clean": true
      }
    },
    {
      "id": 25,
      "type": "collect",
      "params": {
        "pulse": {
          "$ref": 24
        }
      },
      "data": {
        "marks": [
          "input"
        ]
      }
    },
    {
      "id": 26,
      "type": "mark",
      "params": {
        "markdef": {
          "marktype": "rect",
          "name": "marks",
          "role": "mark"
        },
        "interactive": true,
        "clip": false,
        "context": {
          "$context": true
        },
        "groups": null,
        "parent": null,
        "index": 0,
        "pulse": {
          "$ref": 25
        }
      }
    },
    {
      "id": 27,
      "type": "encode",
      "params": {
        "pulse": {
          "$ref": 26
        },
        "encoders": {
          "$encode": {
            "update": {
              "$expr": "var o=item,datum=o.datum,$;o[\"fill\"]=\"#4c78a8\";o[\"tooltip\"]={\"IMDB_Rating (binned)\":(((datum[\"bin_maxbins_10_IMDB_Rating\"]===null)||isNaN(datum[\"bin_maxbins_10_IMDB_Rating\"]))?\"null\":((this.format(datum[\"bin_maxbins_10_IMDB_Rating\"],\"\")+\" - \")+this.format(datum[\"bin_maxbins_10_IMDB_Rating_end\"],\"\"))),\"Count of Records\":this.format(datum[\"__count\"],\"\")};o[\"x2\"]=((datum[\"bin_maxbins_10_IMDB_Rating\"]===null)||isNaN(datum[\"bin_maxbins_10_IMDB_Rating\"]))?0:_[\"%x\"](datum[\"bin_maxbins_10_IMDB_Rating\"])+1;o[\"x\"]=((datum[\"bin_maxbins_10_IMDB_Rating\"]===null)||isNaN(datum[\"bin_maxbins_10_IMDB_Rating\"]))?0:_[\"%x\"](datum[\"bin_maxbins_10_IMDB_Rating_end\"]);o[\"y\"]=_[\"%y\"](datum[\"__count\"]);o[\"y2\"]=_[\"%y\"](0);if(o.x>o.x2)$=o.x,o.x=o.x2,o.x2=$;o.width=o.x2-o.x;if(o.y>o.y2)$=o.y,o.y=o.y2,o.y2=$;o.height=o.y2-o.y;return 1;",
              "$fields": [
                "bin_maxbins_10_IMDB_Rating",
                "bin_maxbins_10_IMDB_Rating_end",
                "__count"
              ],
              "$output": [
                "fill",
                "tooltip",
                "x2",
                "x",
                "y",
                "y2"
              ]
            },
            "enter": {
              "$expr": "var o=item,datum=o.datum,$;return 1;",
              "$fields": [],
              "$output": []
            }
          }
        },
        "%x": {
          "$ref": 10
        },
        "%y": {
          "$ref": 11
        },
        "parent": {
          "$ref": 9
        }
      }
    },
    {
      "id": 28,
      "type": "bound",
      "params": {
        "mark": {
          "$ref": 26
        },
        "pulse": {
          "$ref": 27
        }
      }
    },
    {
      "id": 29,
      "type": "render",
      "params": {
        "pulse": {
          "$ref": 28
        }
      },
      "data": {
        "marks": [
          "output"
        ]
      }
    },
    {
      "id": 30,
      "type": "sieve",
      "params": {
        "pulse": {
          "$ref": 29
        }
      },
      "parent": {
        "$ref": 8
      },
      "data": {
        "marks": [
          "values"
        ]
      }
    },
    {
      "id": 8,
      "type": "viewlayout",
      "params": {
        "legends": {
          "$ref": 5
        },
        "autosize": {
          "$ref": 4
        },
        "mark": {
          "$ref": 0
        },
        "pulse": {
          "$ref": 7
        }
      }
    },
    {
      "id": 31,
      "type": "bound",
      "params": {
        "mark": {
          "$ref": 0
        },
        "pulse": {
          "$ref": 8
        }
      }
    },
    {
      "id": 32,
      "type": "render",
      "params": {
        "pulse": {
          "$ref": 31
        }
      }
    },
    {
      "id": 33,
      "type": "sieve",
      "params": {
        "pulse": {
          "$ref": 32
        }
      },
      "data": {
        "root": [
          "values"
        ]
      }
    }
  ],
  "streams": [],
  "updates": [],
  "bindings": [],
  "eventConfig": {
    "defaults": {
      "allow": [
        "wheel"
      ]
    }
  }
}
```
</details>

You should be able to see the transforms inside the collection of operators. For example, the nodes with ids 15, 16, and 17 are the `extent`, `bin`, and `aggregate` transforms for creating the histogram.

**Comment by saulshanabrook** [comment]
> Are you proposing to bypass the Vega-Lite JavaScript library entirely and write your own VL->Vega compiler? Or did I completely miss something here?

That part will happen in Javascript, using the regular Vega Lite library. Since we are operating in a notebook, we can communicate back and forth between Javascript and Python using [Jupyter's Comms](https://jupyter-notebook.readthedocs.io/en/stable/comms.html). So the tentative plan is:

1. User composes Altair chart object in Python based on ibis expression
2. This is compiled to Vega Lite, passed to JS, transformed to Vega, and passed back to Python.
3. Now we transform the Vega spec in Python, consolidating some of the transforms into a new one that uses a custom `ibis` transform.
4. Then we send this back to JS, where it is rendered using the Vega library, with our custom `ibis` transform registered. This transform will asynchronously send the required inputs back to Python, where they will be used to create the final query, then executed, and then the resulting data passed back.

> (I'm assuming the transform extraction and re-writing is happening at the Vega, not Vega-Lite level, though either is possible in theory, given appropriate support from an underlying layer.)

We were doing it at the Vega-Lite level before, and now we are moving to the Vega level.

> Regarding your earlier post about where the transforms reside

Thanks for this example. I went back and looked at my code, and I realized I had a bug where I was calling `vega.parse` on the wrong object, so was getting a pretty empty graph. Now when I call it on the right Vega spec, I get the right one [and can see the transforms](https://github.com/Quansight/explore-vega/blob/8f1b7620c175a5c17dcd22f54433c1c5e7bc6dba/graph.json#L151-L183).

So an alternative approach would be to transform this graph, instead of the Vega spec.

**Comment by domoritz** [comment]
How are you going to support interactions in this model?

**Comment by saulshanabrook** [comment]
@domoritz In step 4, we are executing a vega spec with a custom transform in it that will fetch new data. This will get executed as the user interacts and changes signal values.

**Comment by saulshanabrook** [comment]
My next step here is to explore how the Vega graph looks like for a custom transformation. And to play with this to see how inlining a filter would work on the graph level.

**Comment by saulshanabrook** [comment]
If I have a Vega spec with some data that is not referenced in it at all, I would assume the transforms on it should never be run. For example, this spec:

https://gist.github.com/saulshanabrook/d3371a76234f9059b9926f2162fb41a1

The data `6132438473295640038` is never referenced and so could be "garbage collected" from the chart, but the transform on it still seems to be run. Is this intentional? How hard is it to find out if a dataset is no longer necessary?

The idea being that before, there was another data item that used that as a source, but then we collapsed that one, so now the dataset has no references to it. This was the input vega spec: https://gist.github.com/saulshanabrook/cf66ade69f8041eaf25b4d486882b2b6 You see that we replaced the second dataset with a `queryibis` transform.

**Comment by jheer** [comment]
The Vega parser does not perform any analysis or optimization for the case of an "unused" data source. There was never a need in the past (e.g., why would someone define a dataset and never use it?), and the current design would still make the unused dataset accessible via the runtime View API. So, if you are going to rewrite a JSON spec, it is currently the responsibility of the rewrite logic to perform a static analysis pass and "clean up" any datasets that are no longer needed.

**Comment by saulshanabrook** [comment]
@jheer Thanks for the explanation, that makes sense. Do you have an intuition on whether it would be easier to do that kind of analysis on the vega spec or the vega graph?

**Comment by jheer** [comment]
I don't think one would necessarily be harder than the other. That said, I'd recommend analyzing the spec, as it is covered by a formal schema, versioning, etc, whereas the dataflow graph description is an internal representation that could be subject to change -- even though we currently have no plans to change it!

**Comment by ian-r-rose** [comment]
I'm running into a bit of trouble with reasoning about vega expressions that involve selection elements. In particular, vega-lite charts that are compiled to vega seem to get an unfamiliar function `vlSelectionTest` and a related `vlSelectionResolve`, which are not documented [here](https://vega.github.io/vega/docs/expressions).

Some snooping around the vega codebase seems to indicate that they are relatively recent functions, but it's not really clear to me what their intention is, or how to think about vega-lite-related functionality cropping up in a vega spec.

Vega examples that have not gone through the vega-lite pipeline, such as [this](https://vega.github.io/vega/examples/population-pyramid/) one, seem to use a somewhat different approach to selections. So I guess I am wondering (1) How should I think about these `vlSelection` functions? and (2) is there a way to transform a spec using them into one that does not?

**Comment by domoritz** [comment]
cc @arvind

**Comment by saulshanabrook** [comment]
I was able to get this working now, see https://github.com/ian-r-rose/vega-ibis-transform/blob/06ce7e4b70d1833c5546d4488c109957d826954a/ibis_vega_transform/vegaexpr.py#L237-L301 for the Python translation of `vlSelectionResolve` that maps to ibis statements.

It isn't the prettiest, but currently I am just replacing the references to things like `data("Filter_store")` with the actual value of filter store when the transform is run and we have access to that data.

**Comment by saulshanabrook** [comment]
Do you know if there are any existing methods to move domain sorting to a transform? In [this example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzI8caIKlIx0wFoGATgBMiBq4AcBPtD4ARgDsrp4AbOKIzgQ+AKyxAIxM0ASufGGQBhBiUrJYkAFSkKyGkATwcJTI8OhYoBDZAB7m1ACeajb5AI5a4vCqpqq4NiLiqKiSBKgmnVBwWv2ZJQ1QrXKGK5BtHbbwsKLV4krFGw2QKARKlLawkmjVAPoAzoMjp9lPt7x1ZRWwVTVbM0RLdKARJLYwU8UvAAehBKcERAslAACTQzgSWw8ahqJ4YAD0BOG0wAdKhkHQtAFSchYASMQQJMSpuIHEpKQRiXxSa5SQlSQArT7wE7ZeziJ4EahPdabCVONweby+fzBUKuCJRGIEeJJFJpDJYADa7zIt3u8Ger1sABUABpLM04C0Uq0vGa2ACyABEnSsIC67m7rZ78g7-QGg5bQ9RZpBfZGVtGQx647YAHIANSTDRTjzT8dtGdzgcgroLNvyAGEAIKl83BythqARlHJ8tN91V1uO9t5zsxwt2vvLKOD1M9hN+-tlivdluQOsN-ML9Ph0fOifN9dQbMr7dr+OJ2eNodT5en1ex48ASQP85vI4fXaf4ZLV8Pb73Oc-j+H+Revef6vgBUCXmOHb-lOADyAASL7nou+4gUhu6QPBiGTshv6QQO0GLm2eFzqBF71qh2HoUBWE7vGMEAEo0UedofsRZ6UfGEFbgR6HFkx36QER3GkYRrHCWhnHkWx15gRhCEUbRma4eJHEsfxslCQG7GKRu6lTpp448XR8nSV+sm1gAWnpi4nqZRm2FxWkyfpYlOWZ+mbm59m6QpzH5Ax1lUcBdkibxnmGaFRauRFEkOVJKk6b2gXxihIWxfklnJd6wUJX5UAAArxV5kW2DBADSWUZVZvkCXxNXmdVaWqf5FX1VOmVtTZOXFel4FFTFzVQOVmSnAAuoYCKCEAA) the domain sorts an aggregate count. I would like to move this aggregation out of the domain and into a data transform. I am planning on just doing this manually with some more pre-processing, but I wanted to see if you knew of any existing functionality that would do this for us. I tried running it through VL's `extractTransform` but it still seemed to stay in the domain.

**Comment by domoritz** [comment]
We don't have a way right now but in the example you posted, we could instead sort by the `__count` field. The idea is that we would just reuse the count aggregate that we already have. I think this is something we could change in the Vega-Lite compiler. 

See [this spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJADujAy10AWAAwe7UWHgCeADY6OJDwyIGBxvYG6HiYOADaShCgEOlQMuioIVCx8QC0bgCcAEwAZm6lABzIAMzwdewA7KVVAGzo5cXItaKiAIwe4aV17dEZUBTogazIsLrJk+nAkNwAToxMMgD6fnG5kAAqABqQAL4+y6sbW5Z78XiHALIAIhdXkzeb2w8HusczpcUl81j97vsngC3h8QRlvnddpDDgA5ABqsOWqTBiL+UNCRxRmKxCN+yIBAGEAILE644smPQ6nWmg24M-4EoGfeH0iGMgHM4FYsCkvkcqAwoUk3lI-mhaksnlssX4qCC7krGV41EYqV05Wy8WQSUa7EG7WUml61ngw2q40ASUVmvN5M5zrNtotBKJ1qVXrdUHRHpFWsDjpDorthwVfpdAblUAA8gAJSNhxOQYNxz248Op9OuzPZ02hotG9Vw+N5zOx0tR70Sp05ssJo1JgBKhbb9sJ3ZrRrrVdz7N7vvrGYrXOHrYHY-7o5jVon5ftBZbDfDJZnm8zfY3k970+Fu6nC5VTOP0tXh3XK57hypAC1z9Hoe8DzfLa-G8dxzvD0vH9w0rE9AIBTtgMzZ5m3vOcgM-B8BX-MCv3lZcALQtUr31JDQm3VC8KgZ8oKNGDSPtAAFDDCPgiCAGkKMfF9ELon0mIBEjWMXBiONCLi4J40JyO4i9v1Et9QiTRjzirABdEFrTSSZICyHIAXydAdg8CYMkgaRWHWcINLidAijKSoanqRoWjaUpOm6XpkH6IYRjGXT0kgPB1nQGRYHKDZUEWHcZ3sAJCEOdBqGodZhChUt7Bi7hWEIdh-EWcC5ISqBuGIDL4GSmQ8EgLLQqgcpGAiAwFiSGRWEiUrhXsdAarARJIB2HYCtYIqSpnWTlgUjIBrARrfC2LJAlapZNTUw5-AeZBCAUKYZjmXRSg8JSq1U7JDhQLZ8A8+wUvyQ52F86r9HCAAKAxuAwSwboAcn8Z6AEo6GCKwWHkMAPDoAY-oBjxRHesAACowAWvwlsgRSlDGyAMHWABraaQWUvS5oBFH0eOqBwsOWL4GKjV9ICYIMou9YSvJ8p1ge3RVk0kz4m051IGQGQCoMXIsZU07xQF5ZIAqyJmcgaZZkOABiNx4Gaap0GqEN7AAD0lhAZkOTW-rFyrAiMUJOu63qWw10otfgHWAT11aZd0LbssgdKcFWbWqdCdL9YqqqAS-C3cGQQ7ivd-Sba9qAfagC6ZGNsBvLmEblhT9I05GpHPfmYL4R2nHQj1naiYBQJLGQdBafJ+7HrkcPWdCTSOd9w2E46rrCuKuNIB8qxckSbxQw0ahJoBJwXEQC4xuxxhjJwJPkHJ7RGd0BfFM+EXMj2gEfeL-wIoBOOjGrh70EsZmZ0gBu8lM5vL79o2A6Q0t9I2MOy2W0Icl8lawT52nG7zHCPHSw1gW7+xNh3HqXcqzd17tQfmFM4bh2HqPb2i1lrnG7mYCwVgHQyBkMgAB-1AbkxwaApMqgiFOzoKDBGEAkboHVjnJImMdrZztgTHE3N36QHYNwAgTNyYxWcLocoMxYCL2LswKOkAKSdzANwcoYAOzIAKusaqXDAjoHYBEAAYrMWAk957rDmOTbRujAhJioOsbRn9E6mKkaLPAs9UbyOgVrCaMwAThEYIEG648WCkE8O9TmmhLB801jgAY682Giw4YXLhtweGHwEWoIKwjNgGAAMqR3mlwkRCcF7kxcfANxndPEj28aEXx-jAmIGCR4UJ3ca5nzrmAcRU0nEqQsREVqnTJHkwwOrAAourJ4vUcDeB2qgSwYyJnv2mc41x-SJHdL0uE+OyAon-ViXneJeSd5JM2Ck0IwRyhkx2oUsRaySkyMOF+JeETtm6BicNRGIBzhAA) for what I think we should be doing.

**Comment by domoritz** [comment]
I created https://github.com/vega/vega-lite/issues/4990 to note down the idea.
