### ISSUE TITLE
Create conda package with JL included

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight/jupyterlab-omnisci#58]
It would be nice to have a way for users to install this without having to run webpack to rebuild jupyterlab.

One way to do that is to build a custom JL package on conda that has this extension preinstalled, like: https://github.com/jonmmease/jupyterlab_delux

**Comment by saulshanabrook** [comment]
In our meeting, we laid out two paths we can go on.

1. Create conda package that includes JL extension as well as ibis and python package. Installing this will rebuild your jupyterlab instance and add this extension.
2. Create conda package that contains new distribution of jupyterlab with extension already included, as well as Python package. This means when you install it, you don't have to run a `jupyter lab build`, and you would use an alternative CLI, like `jupyterlab-omnisci` or `omniscilab` (?). This is the `jupyerlab_delux` option.


@gnestor and I are going to work on this.

**Comment by niviksha** [comment]
@saulshanabrook @gnestor any updates here? would love to be a trial user :-) when you're ready.

**Comment by saulshanabrook** [comment]
@gnestor should this be closed?

**Comment by gnestor** [comment]
Yep!
