### ISSUE TITLE
Jupyter Lab's dark mode doesnt seem to work well with Altair+Ibis charts

### ISSUE THREAD

**Issue by niviksha** [Quansight/jupyterlab-omnisci#66]
Although altair seems to now have this, (and it looks nice :-) ), the jupyter lab dark mode setting seems to hide all chart labels when we use `alt.renderers.enable('ibis')` **_after_** setting `alt.renderers.set_embed_options(theme='dark')`

See https://github.com/altair-viz/altair/issues/742

**Comment by ian-r-rose** [comment]
Thanks for bringing this up @niviksha.

When rendering traditional PNG/SVG images, JupyterLab can check for an optional metadata parameter that hints at whether the image should have a light or a dark background. I think we can do something similar here. It should be relatively straightforward to add something similar to our renderer. We should also probably try to upstream that to Altair.
