### ISSUE TITLE
[BUG] Charting Example Broken First Select

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight/jupyterlab-omnisci#77]
**Describe the bug**
If I click on the first bar in the left chart in the charting example, it selects another bar and overlays it. 

**To Reproduce**
1. Go to https://mybinder.org/v2/gh/Quansight/jupyterlab-omnisci/3bd4c64?urlpath=lab/tree/notebooks/Charting%20Example.ipynb
2. Run all cells
3. Wait for the chart to load
4. Click on the first line, saying "CA"

**Expected behavior**
It should select that whole line, but instead it just selects a little bar

**Screenshots**
<img width="1406" alt="Screen Shot 2019-07-27 at 4 22 54 PM" src="https://user-images.githubusercontent.com/1186124/61999250-e24a3400-b08a-11e9-9159-037b8969d831.png">

@domoritz Do you have any ideas on this one? Seems to be on the vega side?

**Comment by domoritz** [comment]
Hmm, I looked at the notebook and also the generated Vega-Lite and it looks right. It seems like somehow there is an added group by so that the bars are being stacked.
